name: Build APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip openjdk-17-jdk build-essential libssl-dev libffi-dev zlib1g-dev git zip unzip autoconf libtool pkg-config cmake lld patchelf
          pip3 install --upgrade pip
          pip3 install buildozer cython==0.29.33

      - name: Patch buildozer root check
        run: |
          BZ=$(python3 -c "import buildozer; print(buildozer.__file__)")
          sed -i "s/cont = input('Are you sure you want to continue \[y\/n\]? ')/cont = 'y'/" $BZ

      - name: Build APK
        run: |
          cd $GITHUB_WORKSPACE
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: detector-metais-apk
          path: bin/*.apk
